name: advy_flutter_sdk
description: "A advy flutter sdk plugin."
version: 1.0.1
homepage: "https://github.com/advy-sdk/flutter.git"
repository: "https://github.com/advy-sdk/flutter.git"

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.advy.sdk.flutter.advy_flutter_sdk
        pluginClass: AdvyFlutterSdkPlugin
      ios:
        pluginClass: AdvyFlutterSdkPlugin